apiVersion: fleet.cattle.io/v1alpha1
kind: Bundle
metadata:
  name: wordpress-traefik-bundle
  namespace: fleet-local
spec:
  clusterSelector:
    matchLabels:
      management.cattle.io/cluster-name: fleet-local
  resources:
    - name: traefik
      namespace: traefik
      targetNamespace: traefik
      chart:
        name: traefik
        version: 10.3.0
        repo: https://helm.traefik.io/traefik
        valuesFile: ./charts/traefik/values.yaml
    - name: wordpress
      namespace: wordpress
      targetNamespace: wordpress
      chart:
        name: wordpress
        version: 11.0.0
        repo: https://charts.bitnami.com/bitnami
        valuesFile: ./charts/wordpress/values.yaml
