apiVersion: v1
kind: Service
metadata:
  name: blog-jtmb-mysql-service
  namespace: wordpress-stack
spec:
  selector:
    app: blog-jtmb-mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP