apiVersion: v1
kind: Service
metadata:
  name: calibre-service
  namespace: media-stack
spec:
  selector:
    app: calibre
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: ClusterIP
