apiVersion: v1
kind: Service
metadata:
  name: qbit-monitor-service
  namespace: torrent-stack
spec:
  selector:
    app: qbit-monitor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
