apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hookie-pvc
  namespace: hookie
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn  # Explicitly set Longhorn as the storage class
