# Traefik values.yaml

# Enable Traefik as an ingress controller
deployment:
  enabled: true

# IngressClass configuration
ingressClass:
  enabled: true
  name: traefik

# Set entry points for HTTP and HTTPS (use web, websecure)
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

# Enable Let's Encrypt for TLS
certificatesResolvers:
  letsencrypt:
    acme:
      email: your-email@example.com
      storage: /data/acme.json
      httpChallenge:
        entryPoint: web

# Traefik dashboard settings (optional)
dashboard:
  enabled: true
  domain: "traefik.jtmb.cc"  # Change to your desired domain for the dashboard
  ingressClassName: traefik

# Set to true to expose the Traefik dashboard
metrics:
  prometheus:
    enabled: true
