apiVersion: v1
kind: PersistentVolume
metadata:
  name: smb-plex-pv
  labels:
    app: longhorn-test-cifs
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - uid=33
    - gid=33
    - file_mode=0755
    - dir_mode=0755
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: "smb-plex-share"
    volumeAttributes:
      source: "//192.168.0.3/backups"
    nodeStageSecretRef:
      name: cifs-secret
      namespace: default
