apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smb-plex-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: smb-plex-pv
  storageClassName: ""
