---
kind: Service
apiVersion: v1
metadata:
  name: longhorn-test-cifs-svc
  namespace: default
spec:
  selector:
    app: longhorn-test-cifs
  clusterIP: None
  ports:
  - name: netbios-port
    port: 139
    targetPort: 139
  - name: microsoft-port
    port: 445
    targetPort: 445