apiVersion: v1
kind: Service
metadata:
  name: blog-jtmb-service
  namespace: wordpress-stack
spec:
  selector:
    app: blog-jtmb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP