apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: torrent-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      containers:
        - name: qbittorrent
          image: lscr.io/linuxserver/qbittorrent:latest
          env:
            - name: PUID
              value: "0"
            - name: PGID
              value: "0"
            - name: TZ
              value: "America/New_York" # Replace with your timezone
            - name: WEBUI_PORT
              value: "8112"
            - name: QBITTORRENT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: qbittorrent-login-secret
                  key: qbittorrent-username
            - name: QBITTORRENT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: qbittorrent-login-secret
                  key: qbittorrent-password
          ports:
            - containerPort: 8112
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /config
            - name: downloads
              mountPath: /media_drive
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: qbittorrent-config-pvc
        - name: downloads
          persistentVolumeClaim:
            claimName: qbittorrent-samba-pvc