apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent-vpn
  namespace: torrent-stack
  annotations:
    reloader.stakater.com/auto: "true"  # This will automatically trigger reloads if config changes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent-vpn
  template:
    metadata:
      labels:
        app: qbittorrent-vpn
    spec:
      containers:
        - name: qbittorrent
          image: lscr.io/linuxserver/qbittorrent:latest
          env:
            - name: PUID
              value: "0"
            - name: PGID
              value: "0"
            - name: TZ
              value: "America/New_York"
            - name: WEBUI_PORT
              value: "8112"
          ports:
            - containerPort: 8112
              name: webui
              protocol: TCP
            - containerPort: 6881
              name: bittorrent
              protocol: UDP
          volumeMounts:
            - name: config
              mountPath: /config
            - name: downloads
              mountPath: /media_drive

          
        - name: gluetun
          image: qmcgaw/gluetun
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          env:
            - name: VPN_SERVICE_PROVIDER
              value: protonvpn
            - name: OPENVPN_USER
              valueFrom:
                secretKeyRef:
                  name: protonvpn-credentials
                  key: openvpn_user
            - name: OPENVPN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: protonvpn-credentials
                  key: openvpn_password
            - name: VPN_TYPE
              value: openvpn
            - name: PORT_FORWARD_ONLY
              value: "on"
            - name: VPN_PORT_FORWARDING
              value: "on"
            - name: VPN_PORT_FORWARDING_PROVIDER
              value: protonvpn
            # - name: FIREWALL_VPN_INPUT_PORTS
            #   value: "8112,6881"
            - name: FIREWALL_INPUT_PORTS
              value: "80,443,8112"
            # - name: VPN_NO_DEFAULT_ROUTE
            #   value: "false"  # Prevents VPN from routing all traffic
            # - name: VPN_ROUTES
            #   value: "6881/udp"  # Route only torrent traffic (port 6881 for UDP)
            # - name: VPN_GATEWAY
            #   value: "yes"  # Ensure the VPN gateway is used for the selected traffic
          volumeMounts:
            - name: config
              mountPath: /config
            - name: downloads
              mountPath: /media_drive
          lifecycle:
            postStart:
              exec:
                command:
                  - "/bin/sh"
                  - "-c"
                  - |
                      # iptables rule to ensure WebUI (port 8112) doesn't go through VPN
                      iptables -t mangle -A PREROUTING -p tcp --dport 8112 -j ACCEPT
                      # iptables rule to route torrent traffic (6881/udp) through VPN
                      iptables -t mangle -A PREROUTING -p udp --dport 6881 -j MARK --set-mark 1
                      
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: qbittorrent-config-pvc
        - name: downloads
          persistentVolumeClaim:
            claimName: qbittorrent-samba-pvc
