apiVersion: v1
kind: Service
metadata:
  name: qbittorrent-service
  namespace: torrent-stack
spec:
  type: ClusterIP
  selector:
    app: qbittorrent-vpn
  ports:
    - protocol: TCP
      port: 8112
      targetPort: 8112