apiVersion: v1
kind: Service
metadata:
  name: qbittorrent-service
  namespace: torrent-stack
spec:
  selector:
    app: qbittorrent
  ports:
    - protocol: TCP
      port: 8112
      targetPort: 8112
  type: ClusterIP