apiVersion: v1
kind: Service
metadata:
  name: qbittorrent-service
  namespace: torrent-stack
spec:
  selector:
    app: radarr
  ports:
    - protocol: TCP
      port: 7878
      targetPort: 7878
  type: ClusterIP