apiVersion: fleet.cattle.io/v1alpha1
kind: Bundle
metadata:
  name: fleet-gen-bundle
  namespace: fleet-local
spec:
  clusterSelector:
    matchLabels:
      management.cattle.io/cluster-name: fleet-local
  resources:
    - path: ./hookie/fleet.yaml
    - path: ./media-stack/fleet.yaml
    - path: ./torrent-stack/fleet.yaml