apiVersion: fleet.cattle.io/v1alpha1
kind: Bundle
metadata:
  name: hookie-bundle
  namespace: fleet-local
spec:
  clusterSelector:
    matchLabels:
      management.cattle.io/cluster-name: fleet-local
  resources:
    - path: ./manifests/*
  diff:
    comparePatches:
      - apiVersion: fleet.cattle.io/v1alpha1
        kind: GitRepo
        name: "*"
        operations:
          - {"op": "remove", "path": "/spec/helm/releaseName"}
          - {"op": "remove", "path": "/spec/helm/targetNamespace"}
