apiVersion: fleet.cattle.io/v1alpha1
kind: Bundle
metadata:
  name: hookie-bundle
  namespace: fleet-local
spec:
  clusterSelector:
    matchLabels:
      management.cattle.io/cluster-name: fleet-local
  resources:
    - path: ./manifests/*
    - path: ./values.yaml  # Ensure it's explicitly added
