apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config-pvc
  namespace: media-stack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn # Explicitly set Longhorn as the storage class

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-samba-pv
spec:
  capacity:
    storage: 1Gi # Updated to reflect a larger capacity
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: sonarr-samba-share
    volumeAttributes:
      source: "//10.10.68.155/smb_share" # Explicitly define the source field
      options: "uid=0,gid=0,forceuid,forcegid,file_mode=0755"
    nodeStageSecretRef:
      name: samba-secret
      namespace: media-stack

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-samba-pvc
  namespace: media-stack
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: sonarr-samba-pv
  storageClassName: "" # Ensures it binds to the manually created PV
