---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-media-stack
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: james.branco@gmail.com # Replace with your email address
    privateKeySecretRef:
      name: letsencrypt-media-stack
    solvers:
      - http01:
          ingress:
            class: nginx #CHANGE