apiVersion: v1
kind: Namespace
metadata:
  name: wordpress-stack

---

apiVersion: v1
kind: Namespace
metadata:
  name: hookie

---

apiVersion: v1
kind: Namespace
metadata:
  name: media-stack

---

apiVersion: v1
kind: Namespace
metadata:
  name: wordpress-stack
