apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared-tunnel
  namespace: cattle-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared-tunnel
  template:
    metadata:
      labels:
        app: cloudflared-tunnel
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:latest
          command:
            - "cloudflared"
            - "tunnel"
            - "--no-autoupdate"
            - "run"
            - "--token"
            - "$(TUNNEL_TOKEN)" # Direct environment variable substitution
          env:
            - name: TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflare-tunnel-secret
                  key: TUNNEL_TOKEN
docker run cloudflare/cloudflared:latest tunnel --no-autoupdate run --token eyJhIjoiZTMwNDhmNDI0Y2JiNjAzNWM2ZWEwNGQ0NmZjMTdlYTgiLCJ0IjoiN2NhZGU0MDYtZmM4Mi00YTY0LWE5NTUtM2Y4NmY0ZWViOGUzIiwicyI6Ik16SXhaR1psTURBdE9HWmhZeTAwWmpNNUxUa3lNVFV0Wm1RMll6SmhZalpsWmpndyJ9