apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blog-jtmb-redis-config-pvc
  namespace: wordpress-stack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn  # Explicitly set Longhorn as the storage class