apiVersion: v1
kind: Service
metadata:
  name: gluetun-service
  namespace: torrent-stack
spec:
  selector:
    app: gluetun
  ports:
    - protocol: TCP
      port: 8112
      targetPort: 8112
  type: ClusterIP