apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config-pvc
  namespace: media-stack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn  # Explicitly set Longhorn as the storage class

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-samba-pv
spec:
  capacity:
    storage: 100Gi # Updated to reflect a larger capacity
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: radarr-samba-share
    volumeAttributes:
      cifsUrl: 
        secretRef:
          name: samba-secret
          key: source
      options: 
        secretRef:
          name: samba-secret
          key: mountOptions