apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config-pvc
  namespace: media-stack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn  # Explicitly set Longhorn as the storage class

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-samba-pv
spec:
  capacity:
    storage: 1Gi # Updated to reflect a larger capacity
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: radarr-samba-share
    volumeAttributes:
      source: "//$(SMB_IP)/plex_smb_share"  # Explicitly define the source field
      options: "uid=0,gid=0,forceuid,forcegid,file_mode=0755"
    nodeStageSecretRef:
      name: samba-secret
      namespace: media-stack 

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-samba-pvc
  namespace: media-stack
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: radarr-samba-pv
  storageClassName: ""  # Ensures it binds to the manually created PV
