apiVersion: apps/v1
kind: Deployment
metadata:
  name: nzbgett
  namespace: media-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nzbgett
  template:
    metadata:
      labels:
        app: nzbgett
    spec:
      containers:
        - name: nzbgett
          image: linuxserver/nzbget
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/New_York" # Replace with your timezone
          ports:
            - containerPort: 6789
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: nzbgett-config-pvc
