apiVersion: v1
kind: Service
metadata:
  name: nzbgett-service
  namespace: media-stack
spec:
  selector:
    app: nzbgett
  ports:
    - protocol: TCP
      port: 9117
      targetPort: 9117
  type: ClusterIP
